### ISSUE TITLE
Reading the Sqids FAQ, encoding Negative Integers *must* not be allowed

### ISSUE THREAD

**Issue by danieleteti** [sqids/sqids-pascal#1]
Thank you for your great Sqids implementation.
I'm integrating it in the next DMVCFramework version.

Reading the [Sqids FAQ](https://sqids.org/faq#limitations) seems that negative numbers should not be threaded by the encoding; must not be possibile to encode. However this implementation allows it. 
There is some reason to do that?

Thank you

**Comment by dokkie8844** [comment]
Thank you for your kind feedback and your question!

It is correct that a Sqids implementation should handle non-negative numbers only. This is enforced by the TNumber type, which is equivalent to the UInt64 type. Like a Word or Cardinal, the UInt64 type is unsigned and, thus, non-negative. As a result, the compiler enforces that the Sqids implementation handles non-negative integers only.
