### ISSUE TITLE
Generates overflow on $FFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by skamradt** [sqids/sqids-pascal#2]
Using a maximum int64 of $FFFFFFFFFFFFFFFF causes an overflow error when decoding the generated value

```
procedure TTestEncoding.ExtremeValue;
const
  Number: TNumber = $FFFFFFFFFFFFFFFF;
  Id = 'eIkvoXH40Lmd'; // from a previous EncodeSingle
begin
  with TSqids.Create do
  try
    CheckEquals(EncodeSingle(Number), Id);
    CheckTrue(DecodeSingle(id)=Number);
  finally
    Free;
  end;
end;
```

result from test after executing the Decode(id):

```
There was 1 error:
  1) [encoding] TTestEncoding.ExtremeValue: EIntOverflow
     at
      "Integer overflow"
```

**Comment by skamradt** [comment]
Added a pull request which fixes the above problem caused by order of operations.

**Comment by dokkie8844** [comment]
Many thanks for the issue and fix! Will look at them asap later this week.

**Comment by dokkie8844** [comment]
Interestingly, the overflow only happens when using the Delphi compiler. Using FPC, no overflow occurs.
Anyway, I've merged your pull request and added the same test to the FPC test suite. Thank you very much!
